name: Android Builds (APK & AAB)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build APK
        run: |
          flutter config --no-analytics
          flet build apk --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/
          if-no-files-found: error

      - name: Build AAB
        run: |
          flutter config --no-analytics
          flet build aab --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-aab
          path: build/aab/
          if-no-files-found: error
